import 'package:get/get.dart';

import '../gem/state/controller/gem_auth_code_generate_controller.dart';
import '../gem/state/controller/gem_auth_detail_controller.dart';
import '../gem/state/controller/gem_authgst_controller.dart';
import '../gem/state/controller/gem_authsearchlist_controller.dart';
import '../gem/state/controller/gem_bid_controller.dart';
import '../gem/state/controller/gem_maf_data_deatails_controller.dart';
import '../gem/state/controller/gem_maf_home_page_controller.dart';
import '../gem/state/controller/gem_maf_home_page_listing_controller.dart';
import '../gem/state/controller/gem_tender_module_controller.dart';
import '../gem/state/controller/maf_registration_details_controller.dart';
import '../gem/state/controller/maf_registrationform_controller.dart';
import '../network/internet_check_controller.dart';
import '../solar/state/controller/ProjectExecutionFormController.dart';
import '../solar/state/controller/ProjectExecutionRequestListController.dart';
import '../solar/state/controller/banking_partners_controller.dart';
import '../solar/state/controller/digital_request_by_project_id_controller.dart';
import '../solar/state/controller/digital_survey_request_list_controller.dart';
import '../solar/state/controller/finance_customer_project_details_controller.dart';
import '../solar/state/controller/finance_request_list_commercial_controller.dart';
import '../solar/state/controller/finance_request_tracking_controller.dart';
import '../solar/state/controller/finance_requests_lists_controller.dart';
import '../solar/state/controller/go_solar_count_details_controller.dart';
import '../solar/state/controller/project_execution_dashboard_controller.dart';
import '../solar/state/controller/solar_design_count_details_controller.dart';
import '../solar/state/controller/solar_design_request_controller.dart';
import '../solar/state/controller/solar_finance_controller.dart';
import '../solar/state/controller/solar_finance_dashboard_controller.dart';
import '../solar/state/controller/terms_and_condition_controller.dart';
import 'contoller/ISmartCashHistoryController.dart';
import 'contoller/Ismart_coin_history_controller.dart';
import 'contoller/alert_notification_controller.dart';
import 'contoller/app_setting_value_controller.dart';
import 'contoller/auth_contoller.dart';
import 'contoller/battery_management_controller.dart';
import 'contoller/booked_trip_details_controller.dart';
import 'contoller/cash_redemption_options_controller.dart';
import 'contoller/cash_summary_controller.dart';
import 'contoller/catalogue_controller.dart';
import 'contoller/coin_redemption_options_controller.dart';
import 'contoller/coin_to_cashback_conversion_controller.dart';
import 'contoller/coin_to_cashback_submit_controller.dart';
import 'contoller/coin_to_trips_redemption_controller.dart';
import 'contoller/coins_summary_controller.dart';
import 'contoller/common_login_banners_controller.dart';
import 'contoller/consumer_emi_controller.dart';
import 'contoller/create_dealer_electrician_controller.dart';
import 'contoller/credit_debit_note_controller.dart';
import 'contoller/customer_list_controller.dart';
import 'contoller/customer_wise_list_controller.dart';
import 'contoller/dealer_electrician_view_detailController.dart';
import 'contoller/dealer_list_controller.dart';
import 'contoller/dealer_wise_summary_controller.dart';
import 'contoller/distributor_ledger_controller.dart';
import 'contoller/feedback_answer_controller.dart';
import 'contoller/fse_agreement_controller.dart';
import 'contoller/fse_agreement_create_otp_controller.dart';
import 'contoller/fse_agreement_verify_otp_controller.dart';
import 'contoller/help_and_support_controller.dart';
import 'contoller/homepage_banners_controller.dart';
import 'contoller/homepage_promo_videos_controller.dart';
import 'contoller/language_controller.dart';
import 'contoller/luminous_videos_controller.dart';
import 'contoller/new_dealer_electrician_status_controller.dart';
import 'contoller/notification_controller.dart';
import 'contoller/pinelab_redemption_controller.dart';
import 'contoller/price_list_controller.dart';
import 'contoller/primary_billing_controller.dart';
import 'contoller/primary_report_types_controller.dart';
import 'contoller/product_list_controller.dart';
import 'contoller/product_wise_details_controller.dart';
import 'contoller/read_check_alert_notification_controller.dart';
import 'contoller/relationship_controller.dart';
import 'contoller/report_download_for_dealer_controller.dart';
import 'contoller/report_type_controller.dart';
import 'contoller/save_terms_condition_controller.dart';
import 'contoller/scheme_controller.dart';
import 'contoller/scheme_tab_controller.dart';
import 'contoller/secondary_report_distributor_controller.dart';
import 'contoller/splash_screen_controller.dart';
import 'contoller/survey_answer_controller.dart';
import 'contoller/survey_question_controller.dart';
import 'contoller/tertiary_customer_wise_products_controller.dart';
import 'contoller/tertiary_product_wise_details_controller.dart';
import 'contoller/tertiary_report_summary_controller.dart';
import 'contoller/tertiary_sales_combo_controller.dart';
import 'contoller/user_data_controller.dart';
import 'contoller/verify_otp_controller.dart';
import 'contoller/warranty_controller.dart';

Future<void> initControllers() async {
  // initialising getx controillers
  Get.lazyPut(() => SplashScreenController());
  Get.lazyPut(() => UserDataController());
  Get.lazyPut(() => LanguageController());
  Get.lazyPut(() => TertiarySalesHKVAcombo());
  Get.lazyPut(() => WarrantyController());
  Get.lazyPut(() => CashRedemptionOptionsController());
  Get.lazyPut(() => ISmartCashHistoryController());
  Get.lazyPut(() => ConsumerEmiController());
  Get.lazyPut(() => ISmartCoinHistoryController());
  Get.lazyPut(() => CoinToCashbackConversionController());
  Get.lazyPut(() => CoinsSummaryController());
  Get.lazyPut(() => CashSummaryController());
  Get.lazyPut(() => CoinRedemptionOptionsController());
  Get.lazyPut(() => CoinToCashbackSubmitController());
  Get.lazyPut(() => HomepageBannersController());
  Get.lazyPut(() => PriceListController());
  Get.lazyPut(() => CatalogueController());
  Get.lazyPut(() => SchemeController());
  Get.lazyPut(() => VerifyOtpController());
  Get.lazyPut(() => ReportTypeController());
  Get.lazyPut(() => PrimaryReportTypeController());
  Get.lazyPut(() => CoinsToTripController());
  Get.lazyPut(() => CreateDealerElectricianController());
  Get.lazyPut(() => NewDealerElectricianStatusController());
  Get.lazyPut(() => DealerElectricianViewDetailsController());
  Get.lazyPut(() => SecondaryReportDistrubutorController());
  Get.lazyPut(() => ProductWiseDetailsController());
  Get.lazyPut(() => DealerSummaryController());
  Get.lazyPut(() => ProductListController());
  Get.lazyPut(() => TertiaryReportSummaryController());
  Get.lazyPut(() => CustomerWiseListController());
  Get.lazyPut(() => TertiaryCustomerWiseProduct());
  Get.lazyPut(() => TertiaryProductWiseDetails());
  Get.lazyPut(() => PrimaryBillingReportController());
  Get.lazyPut(() => DistributorLedgerController());
  Get.lazyPut(() => CreditDebitNoteController());
  Get.lazyPut(() => DealerList());
  Get.lazyPut(() => CustomerList());
  Get.lazyPut(() => SecondaryReportDealerDownloadController());
  Get.lazyPut(() => LuminousVideosController());
  Get.lazyPut(() => SurveyQuestionsController());
  Get.lazyPut(() => SurveyAnswersController());
  Get.lazyPut(() => AlertNotificationController());
  Get.lazyPut(() => ReadCheckAlertNotificationController());
  Get.lazyPut(() => FseAgreementController());
  Get.lazyPut(() => FeedBackAnswersController());
  Get.lazyPut(() => HomepagePromoVideosController());
  Get.lazyPut(() => BatteryManagementController());
  Get.lazyPut(() => FseAgreementCreateOtpController());
  Get.lazyPut(() => FseAgreementVerifyOtpController());
  Get.lazyPut(() => HelpAndSupportController());
  Get.lazyPut(() => PinelabRedemptionController());
  Get.lazyPut(() => AuthController());
  Get.lazyPut(() => NotificationController());
  Get.lazyPut(() => RelationshipContoller());
  Get.lazyPut(() => BookedTripDetailsController());
  Get.lazyPut(() => CommonLoginBannerController());
  Get.lazyPut(() => SchemeTabController());
  Get.lazyPut(() => SaveTermsConditionController());
  Get.lazyPut(() => AppSettingValueController());

  Get.lazyPut(() => SolarDesignRequestController());
  Get.lazyPut(() => SolarFinanceDashboardController());
  Get.lazyPut(() => SolarDesignCountDetailsController());
  Get.lazyPut(() => BankingPartnersController());
  Get.lazyPut(() => SolarFinanceController());
  Get.lazyPut(() => FinanceRequestsListController());
  Get.lazyPut(() => DigitalSurveyRequestListController());
  Get.lazyPut(() => DigitalRequestByProjectIdController());
  Get.lazyPut(() => TermsAndConditionController());
  Get.lazyPut(() => FinanceCustomerProjectDetailsController());
  Get.lazyPut(() => ProjectExecutionDashboardController());
  Get.lazyPut(() => ProjectExecutionFormController());
  Get.lazyPut(() => FinanceRequestsListCommercialController());
  Get.lazyPut(() => ProjectExecutionRequestListController());
  Get.lazyPut(() => GoSolarCountDetailsController());
  Get.lazyPut(() => InternetController());

  //luminous
  //gem_maf
  Get.lazyPut(() => GemTenderModuleController());
  Get.lazyPut(() => MafRegistrationFormController());
  Get.lazyPut(() => MafRegistrationDetailsController());
  Get.lazyPut(() => GemHomePageController());
  Get.lazyPut(() => GemMafHomePageListingController());
  Get.lazyPut(() => GemMafDataDetailsController());

  //gem_auth
  Get.lazyPut(() => GemAuthGstController());
  Get.lazyPut(() => GemAuthSearchListController());
  Get.lazyPut(() => GemAuthCodeGenerateController());
  Get.lazyPut(() => GemBidController());
  Get.lazyPut(() => GemAuthDetailController());
  Get.lazyPut(() => FinanceRequestTrackingController());

}
